version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-234-28-165.compute-1.amazonaws.com
            database: debk7mod88922k
            user: zbirdmiptqbgvu
            password: de5b01458235941ad6958f50241e9e9668672a4c29dadf23b124e308c304b845
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
